dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  rinkeby:
    eth_usd_price_feed: '0x8a753747a1fa494ec906ce90e9f37563a8af630e'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'